# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpages', to='first_app.Topic'),
        ),
    ]
